### PR TITLE
Load JS/CSS relative to baseURL instead of host

### LINKED ISSUE #134: Site does not render properly as a subdirectory with Hugo 0.101.0
**Describe the bug**

Due to the fix for https://github.com/gohugoio/hugo/issues/9994 which was part of the Hugo 0.101.0 release, sites which use a baseURL such as `https://example.com/subsite/` have the wrong URLs for styles and JavaScript and thus do not render correctly.

**To Reproduce**

Assumes Linux, but equivalent procedure for Windows will do the same thing.

** Steps to reproduce the behavior.**

1. Install Hugo Extended 0.101.0
2. Copy the `exampleSite` from this theme to a new directory (e.g. `~/diary-test`)
3. Change to the `~/diary-test` directory
4. `mkdir themes`
5. `git init`
6. `git submodule add --name diary -- https://github.com/AmazingRise/hugo-theme-diary.git themes/diary`
7. Edit `~/diary-test/config.toml` so that baseURL is `https://example.com/blog/`
8. `hugo --gc`
9. `hugo serve`
10. Open your Browser's developer tools and watch the 'console' tab.
11. Browse to `http://localhost:1313/blog/`
12. In the console observe various missing assets (screenshot below).

**Expected behavior**

The assets should be loaded from under `http://localhost:1313/blog/` (or in case of a live site from under `baseURL`) correctly (no errors).

**Screenshots**

image

**Additional context**

See the discussion on the Hugo forum at <https://discourse.gohugo.io/t/solved-projectname-prefix-is-disappered-in-css-location-info-after-deploy-to-github-pages/40018>

### PR DESCRIPTION
**Pull request by jmooring**
Requires Hugo v0.101.0 or later.
Fixes #134

### CODE REVIEW

**Comment by danielfdickinson** [comment]
**Note**: This will break sites deployed to subdirectories and built with Hugo < v0.101.0. If that is acceptable to @AmazingRise then LGTM. If not then the solution depends on the preferred minimum supported Hugo version.

**Comment by danielfdickinson** [comment]
If you need to support Hugo < v0.83.0 you can use something like:

```
            {{- $hugoVersion := split (replaceRE ".*v?([0-9]+)\\.([0-9]+)\\.([0-9]+).*" "$1 $2 $3" site.Hugo.Version) " " -}}{{- /* We have to use the deprecated .Hugo.Version to support 0.80.0 (or earlier) */ -}}
            {{- if and (eq (int (index $hugoVersion 0)) 0) (ge (int (index $hugoVersion 1)) 101) -}}
                {{- /* no leading slash */ -}}
            {{- else -}}
                {{- /* with leading slash */ -}}
            {{- end  #-}}
```

If >v0.83.0 (but < v0.101.0) support is needed (will work >= 0.101.0 but isn't needed for this case:

```
            {{- $hugoVersion := split (replaceRE ".*([0-9]+)\\.([0-9]+)\\.([0-9]+).*" "$1 $2 $3" hugo.Version) " " -}}
            {{- if and (eq (int (index $hugoVersion 0)) 0) (ge (int (index $hugoVersion 1)) 101) -}}
                {{- /* no leading slash */ -}}
            {{- else -}}
                {{- /* with leading slash */ -}}
            {{- end  #-}}
```

You'd probably want to wrap that in a partial.

HTH

**Comment by AmazingRise** [comment]
Hi, @danielfdickinson and @jmooring 
I'd consider to fix the slash issue just like @jmooring have done and using @danielfdickinson 's method to keep compatibility for legacy Hugo.

Thanks very much for your contribution!

**Comment by AmazingRise** [comment]
BTW `hugo.Version` works both on `0.79` and `0.97.0`. I would prefer `hugo.Version` as the final workaround.

**Comment by danielfdickinson** [comment]
Based on your comment about `hugo.Version`, I did some testing and this is what I am use myself now, in a partial:

```
{{- $hugoVersion := split hugo.Version "." -}}
{{- $verMajor := int (index $hugoVersion 0) -}}
{{- $verMinor := int (index $hugoVersion 1) -}}
{{- $verPatch := int (index $hugoVersion 2) -}}
```
with the full partial which I used to do a pass/fail version check again min and/or max:

```
{{- $ctx := . -}}
{{- $verInRange := true -}}
{{- $hugoVersion := split hugo.Version "." -}}
{{- $verMajor := int (index $hugoVersion 0) -}}
{{- $verMinor := int (index $hugoVersion 1) -}}
{{- $verPatch := int (index $hugoVersion 2) -}}
{{- $minMajor := int (.minMajor | default 0) -}}
{{- $minMinor := int (.minMinor | default $verMinor) -}}
{{- $minPatch := int (.minPatch | default 0) -}}
{{- $maxMajor := int (.maxMajor | default $verMajor) -}}
{{- $maxMinor := int (.maxMinor | default $verMinor) -}}
{{- $maxPatch := int (.maxPatch | default $verPatch) -}}
{{- if lt $verMajor $minMajor -}}
	{{- $verInRange = false -}}
{{- else if and (eq $verMajor $minMajor) (lt $verMinor $minMinor) -}}
	{{- $verInRange = false -}}
{{- else if and (eq $verMajor $minMajor) (eq $verMinor $minMinor) (lt $verPatch $minPatch) -}}
	{{- $verInRange = false -}}
{{- end -}}
{{- if $verInRange -}}
	{{- if gt $verMajor $maxMajor -}}
		{{- $verInRange = false -}}
	{{- else if and (eq $verMajor $maxMajor) (gt $verMinor $maxMinor) -}}
		{{- $verInRange = false -}}
	{{- else if and (eq $verMajor $maxMajor) (eq $verMinor $maxMinor) (gt $verPatch $maxPatch) -}}
		{{- $verInRange = false -}}
	{{- end -}}
{{- end -}}
{{- return $verInRange -}}
```
which can be called with something like

```
{{- if partial "check-hugo-version.html" (dict "minMajor" 0 "minMinor" 101 "minPatch" 0) -}}
   ...do stuff that needs at least 0.101.0...
{{- else -}}
   ...older stuff...
{{- end -}}
```
Hope something in this information can be useful.

**Pull request closed without merging**
