### PR TITLE
#93 add 'extended_head.html' partial

### PR DESCRIPTION
**Pull request by vanhumbeecka**
This PR addresses issue #93 

I've added a custom script in the exampleSite that illustrates how it works.

### CODE REVIEW

**Comment by AmazingRise** [comment]
Hi, vanhumbeecka
Thanks for your support!
But I didn't understand the meaning of this comment:
> Do not put anything in this file - it's only here so that hugo won't throw an error if /layouts/partials/extended_head.html doesn't exist.

Did you mean "Don't remove this file"?

**Comment by vanhumbeecka** [comment]
> Did you mean "Don't remove this file"?
Yes, you are correct. It's actually 2 things: 1) 'do not remove'  and 2) 'don't add anything here'

I just copy pasted this text from the reference hugo theme repository I mentioned earlier.

You can always verify it for yourself: just run the `exampleSite` with the adjusted theme. If you remove this file from the theme, you'll notice the exampleSite will throw an error while running it locally.

**Comment by AmazingRise** [comment]
> Yes, you are correct. It's actually 2 things: 1) 'do not remove' and 2) 'don't add anything here'

Wait... 'extended_head.html' is the very place for users to add contents, and what's the reason for "don't add anything here"? It seems like a contradiction.

**Comment by vanhumbeecka** [comment]
So how this works is as follows:
There are actually 2 files.
* there is the `layouts/partials/extended_head.html` file _in the Theme_
* there is the `layouts/partials/extended_head.html` file _in your own code, using this Theme_

Scenario 1:
If you, as a 'theme-user' don't want to use the 'extended_head' feature, then you don't need to add this file to your own code.
Because in this scenario, there is no _custom_ `extended_head.html` file, it will fallback on the one specified in the _theme_ itself. (because there is still a reference to it in the theme. So it _needs_ to be there)

Scenario 2:
You, as a 'theme-user' want to use this feature, for adding custom scripts (for example) to your site, using this theme.
Now, you need to add your own  `layouts/partials/extended_head.html` in _your own code_ . This will _overwrite_ the placeholder file in the theme itself.

As an example, I've added this 'custom' `extended_head.html` file to the `exampleSite` as well to demonstrate the behaviour.
If you run the `exampleSite`, you'll see it will print out a `console.log` line. That script is only available in the 'custom' html file, specified in the `exampleSite`, showing us that this file will have precedence over the file in the Theme when it's specified.

Hope this clarifies it :) 
It was only by looking at the code in [this Theme repo](https://github.com/panr/hugo-theme-hello-friend/) that i figured out how it worked.

**Comment by AmazingRise** [comment]
OK, got it. Thanks for your clarification.
I'm gonna to merge it.
Again, thanks for your support on this project!

**Pull request merged**
